default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: dbctv_development
test: &test
  <<: *default
  database: dbctv_test

production:
  <<: *default
  database: dbctv_production
  username: #Set these when you deploy
  password:
